name: CI

on:
  push:
    branches:
      - '**'
        
env:
    APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}
    APPLITOOLS_BATCH_ID: ${{ github.sha }}
    APPLITOOLS_SERVER_URL: https://testeyes.applitools.com

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Log Git SHA
        run: echo "$GITHUB_SHA"
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '21.x'    
      - name: Prepare for push event may be use BranchName=${GITHUB_REPOSITORY}/${GITHUB_REF_NAME}
        run: curl -v -L -d '' -X POST "https://testeyes.applitools.com/api/externals/github/push?apiKey=${APPLITOOLS_API_KEY}&CommitSha=${GITHUB_SHA}&BranchName=${GITHUB_REPOSITORY}/${GITHUB_REF_NAME}"
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          working-directory: tutorial-cypress
    
  # batch-completion-notification:
  #   needs: run-tests
  #   if: always()
  #   runs-on: ubuntu-latest
  #   steps:     
  #     - name: Update Applitools batch status 
  #       uses: wei/curl@v1.1.1
  #       with:
  #         args: -d "" -X POST ${{ env.APPLITOOLS_SERVER_URL }}/api/externals/github/servers/github.com/commit/${{ env.APPLITOOLS_BATCH_ID }}/complete?apiKey=${{ secrets.APPLITOOLS_API_KEY }}
     